const { withAppBuildGradle } = require('@expo/config-plugins')

const marker = '// @generated by withProductionSigning'

/** Configure release signing from an external, untracked properties file. */
function withProductionSigning (config) {
	return withAppBuildGradle(config, (mod) => {
		if (mod.modResults.contents.includes(marker)) {
			return mod
		}

		const signingSetup = `${marker}
import java.util.Properties

def signingPropertiesPath = System.getenv("SHIFT_CALENDAR_SIGNING_PROPERTIES")
def signingPropertiesFile = signingPropertiesPath ? file(signingPropertiesPath) : null
def signingProperties = new Properties()
if (signingPropertiesFile?.isFile()) {
    signingPropertiesFile.withInputStream { signingProperties.load(it) }
}

def requiredSigningProperties = ["storeFile", "storePassword", "keyAlias", "keyPassword"]
def hasSigningProperties = signingPropertiesFile?.isFile() && requiredSigningProperties.every {
    signingProperties.getProperty(it)?.trim()
}
def releaseStoreFile = null
if (hasSigningProperties) {
    def configuredStoreFile = signingProperties.getProperty("storeFile").trim()
    releaseStoreFile = file(configuredStoreFile)
    if (!releaseStoreFile.isAbsolute()) {
        releaseStoreFile = new File(signingPropertiesFile.parentFile, configuredStoreFile)
    }
}
def hasProductionSigning = hasSigningProperties && releaseStoreFile.isFile()
`
		let contents = mod.modResults.contents
		const projectRootPattern = /(def projectRoot = rootDir\.getAbsoluteFile\(\)\.getParentFile\(\)\.getAbsolutePath\(\)\r?\n)/
		if (!projectRootPattern.test(contents)) {
			throw new Error('withProductionSigning: unsupported android/app/build.gradle template')
		}
		contents = contents.replace(projectRootPattern, `$1\n${signingSetup}\n`)

		const productionSigningConfig = `        if (hasProductionSigning) {
            release {
                storeFile releaseStoreFile
                storePassword signingProperties.getProperty("storePassword")
                keyAlias signingProperties.getProperty("keyAlias")
                keyPassword signingProperties.getProperty("keyPassword")
            }
		}`
		const signingConfigPattern = /(    signingConfigs \{\r?\n[\s\S]*?)(\r?\n    \})\r?\n    buildTypes \{/m
		if (!signingConfigPattern.test(contents)) {
			throw new Error('withProductionSigning: signingConfigs block not found')
		}
		contents = contents.replace(signingConfigPattern, `$1\n${productionSigningConfig}$2\n    buildTypes {`)
		const withReleaseSigning = `        release {
            if (hasProductionSigning) {
                signingConfig signingConfigs.release
            }`

		const releaseBlockPattern = /        release \{\r?\n            \/\/ Caution![\s\S]*?\r?\n            signingConfig signingConfigs\.debug/m
		if (!releaseBlockPattern.test(contents)) {
			throw new Error('withProductionSigning: release signing block not found')
		}
		contents = contents.replace(releaseBlockPattern, withReleaseSigning)

		mod.modResults.contents = contents
		return mod
	})
}

module.exports = withProductionSigning
